.intel_syntax noprefix

.global	SESSION_CREATE
.global	SESSION_FIND
.global	SESSION_INVALIDATE
.global	TOKEN_SCRATCH
.global	LOGOUT_TOKEN_SCRATCH

.extern	HEX_ENCODE

.section .bss
#===============================================#
#		Session Table (.bss)		#
#===============================================#
	.lcomm	SESSION_TABLE, 2048		# 64 slots x 32 bytes
	.lcomm	TOKEN_SCRATCH, 32		# most-recently-created token (for /login response)
	.lcomm	LOGOUT_TOKEN_SCRATCH, 32	# token extracted from Cookie header (for /logout)

.set	SESSION_SLOT_LEN,	32
.set	SESSION_SLOT_COUNT,	64

.section .text
#===============================================#
#		   SESSION HELPERS		#
#===============================================#
# 1. SESSION_CREATE()
#
# Generates 16 random bytes via getrandom(2), hex-encodes them into
# TOKEN_SCRATCH (32 ASCII hex chars), then copies TOKEN_SCRATCH into the
# first free (all-zero) slot in SESSION_TABLE.
# Returns: rax = 1 (created; TOKEN_SCRATCH holds the active, stored token)
#          OR 0 (table full; TOKEN_SCRATCH holds generated bytes but they
#          were NOT stored - caller must not treat the request as logged in)
SESSION_CREATE:
	sub		rsp,	16
	mov		rdi,	rsp
	mov		rsi,	16
	xor		rdx,	rdx
	mov		rax,	318		# sys_getrandom
	syscall

	mov		rdi,	rsp
	mov		rsi,	16
	lea		rdx,	[rip+TOKEN_SCRATCH]
	call		HEX_ENCODE
	add		rsp,	16

	lea		r8,	[rip+SESSION_TABLE]
	xor		r9,	r9		# slot index
.SC_SCAN:
	cmp		r9,	SESSION_SLOT_COUNT
	jge		.SC_FULL

	mov		rax,	r9
	imul		rax,	rax,	SESSION_SLOT_LEN
	lea		rbx,	[r8+rax]

	# treat an all-zero slot as free (hex-encoded tokens are never all-zero)
	mov		rcx,	qword ptr [rbx]
	or		rcx,	qword ptr [rbx+8]
	or		rcx,	qword ptr [rbx+16]
	or		rcx,	qword ptr [rbx+24]
	cmp		rcx,	0
	jne		.SC_NEXT

	mov		rdi,	rbx
	lea		rsi,	[rip+TOKEN_SCRATCH]
	mov		rcx,	32
	cld
	rep		movsb
	mov		rax,	1
	ret

.SC_NEXT:
	inc		r9
	jmp		.SC_SCAN

.SC_FULL:
	xor		rax,	rax
	ret

# 2. SESSION_FIND(token_ptr=rdi, token_len=rsi)
#
# Scans SESSION_TABLE for a 32-byte slot matching the token at token_ptr.
# Fails immediately if token_len != 32.
# Returns: rax = pointer to matching slot (nonzero), OR 0 if not found.
SESSION_FIND:
	cmp		rsi,	32
	jne		.SF_NO

	lea		r8,	[rip+SESSION_TABLE]
	xor		r9,	r9
.SF_SCAN:
	cmp		r9,	SESSION_SLOT_COUNT
	jge		.SF_NO

	mov		rax,	r9
	imul		rax,	rax,	SESSION_SLOT_LEN
	lea		rbx,	[r8+rax]

	xor		r10,	r10
.SF_CMP:
	cmp		r10,	32
	je		.SF_MATCH
	mov		cl,	byte ptr [rbx+r10]
	mov		r11b,	byte ptr [rdi+r10]
	cmp		cl,	r11b
	jne		.SF_NEXT
	inc		r10
	jmp		.SF_CMP

.SF_MATCH:
	mov		rax,	rbx
	ret

.SF_NEXT:
	inc		r9
	jmp		.SF_SCAN

.SF_NO:
	xor		rax,	rax
	ret

# 3. SESSION_INVALIDATE(slot_ptr=rdi)
#
# Zeroes the 32-byte slot at slot_ptr, returning it to the free pool.
SESSION_INVALIDATE:
	xor		al,	al
	mov		rcx,	32
	cld
	rep		stosb
	ret
